@startuml

rectangle "engage module" {
    interface "service:/api/external/set/engage" as set_engage
    usecase "engage_relay_service"  #LightCoral
}

rectangle "in_parking_task_manager module" {
    interface "service:/in_parking/set/auto_engage" as set_auto_engage
}

(engage_relay_service) --> (set_engage)
(engage_relay_service) <.- (set_engage)
(set_auto_engage) --> (engage_relay_service)
(set_auto_engage) <.- (engage_relay_service)


@enduml